### ISSUE TITLE
请问什么时候能提供显示温度的功能？

### ISSUE THREAD

**Issue by coci713** [eexpress/gs-weather#1]
动画很有意思，但是不能显示温度有点儿小的遗憾，希望能够加入

**Comment by eexpress** [comment]
显示图标的这个Clutter控件，没有hover事件（显示tip）。之前准备采用鼠标移动上去，显示每天的附加信息的。
如果直接把信息固定显示在图标上，又不美观。

**Comment by eexpress** [comment]
好吧。手动实现算了。觉得是应该加上。
![截图 2022-05-21 17-52-53](https://user-images.githubusercontent.com/700793/169646275-1810b695-b78f-430d-9af2-626b44b66ef1.png)

**Comment by coci713** [comment]
非常好的功能，另外有一个小问题，就是我的环境语言设置为中文，但是为什么显示的天气是英文呢？

**Comment by eexpress** [comment]
lang : this.locale, 这是源码。你的locale如果是zh_CN就应该是中文简体的。

**Comment by coci713** [comment]
大概找到原因了，我的/etc/locale.conf内容是LANG=zh_CN.UTF-8，但是代码检测要LANG=zh_CN才会显示中文，但是在系统中这样设置的话，系统无法成为中文环境，所以我直接改了this.locale = "zh_CN",这样就可以显示中文了

**Comment by eexpress** [comment]
今天安装了fedora36，我才发现真有这问题。在ubuntu22.04正常，在f36结果不同。第40行要split一次。
```
this.locale = GLib.get_language_names()[0].split('.')[0];
```

**Comment by eexpress** [comment]
。
